### PR TITLE
Removed atom.symlink from the root

### PR DESCRIPTION
**Pull request by ignazioc**
I removed this symlink from the root of the project because I think is not the right place.

### CODE REVIEW

**Comment by najela** [comment]
Just curious @ignazioc  where do you think atom.symlink should be placed?

**Comment by ignazioc** [comment]
As the readme says everything should be placed in a "topical" folder. In this case my suggestion is to create an "atom" folder and put the symlink inside.

**Comment by holman** [comment]
I think I'm pretty happy with having `atom.symlink` on the top-level. The extra `.symlink` doesn't bother me, and it makes it explicit that it gets symlinked in like the normal workflow is in the repo.

**Comment by ignazioc** [comment]
Fair enough! Thanks

**Pull request closed without merging**
