### PR TITLE
Local modifications to your own gitconfig symlink will be ignored

### PR DESCRIPTION
**Pull request by shanev**
Local modifications to your own gitconfig symlink will be ignored in the repo.

I'm assuming most people are copying gitconfig.sample to gitconfig.symlink and making their changes. The only problem arises is if they actually want to commit their gitconfig.symlink.

### CODE REVIEW

**Comment by danielcompton** [comment]
Sorry to resurrect such an old issue, but what is the reasoning behind ignoring this gitconfig file? If this is to be ignored, is it correct to make modifications to `gitconfig.symlink.example` instead?

**Comment by holman** [comment]
>  I'm assuming to keep username and email out of git?

Yup. Also have run into problems in the past of getting a ton of commits attributed to me, as people would just clone it and go. We ended up opting to going with the `.example` approach instead, so people have to explicitly type in what their details are.

(That said, I thought we had something in the README for all this. You don't want to type in the `.example` file directly; you'll want to copy that file to `gitconfig.symlink` and make your changes there.)

**Comment by danielcompton** [comment]
> You don't want to type in the .example file directly; you'll want to copy that file to gitconfig.symlink and make your changes there.

Sorry, I wasn't very clear here. I meant if I want to make modifications to my gitconfig that will be preserved, they will need to be copied into `.example` so the next time I run `script/bootstrap` they will already be there. The alternative would be to remove the `.gitignore` for that line.

**Comment by holman** [comment]
Ah- I though bootstrap only happens on files if there isn't something symlinked already. i.e., if you re-run it it shouldn't overwrite your good config values.

**Comment by danielcompton** [comment]
You're correct, it won't overwrite existing ones, but on a fresh system, I will need to copy over my gitconfig.symlink from another computer to keep all of my git config. Sorry for the confusion and noise!

**Pull request merged**
