### PR TITLE
Add `brew bundle` completions

### PR DESCRIPTION
**Pull request by alias1**
Added the first level of brew bundle autocompletions. Was going to add the --params for each too, but not sure how to make it work.

### CODE REVIEW

**Comment by holman** [comment]
Nice.

To be honest, this is a section of my dotfiles I totally forgot existed, ha.

Does Homebrew have any "standard" place for all of these, or did you do these manually? For that matter, was the stuff we currently have in here custom as well? I'd prefer to be able to bring in the "full list" if that exists anywhere, otherwise we can just do it ourselves!

**Comment by alias1** [comment]
I just tweaked what was already there, by the looks of it it may have been copied from [Homebrew zsh completions](https://github.com/Homebrew/homebrew/blob/master/Library/Contributions/brew_zsh_completion.zsh) So maybe linking to that would be a better way going forward (though not sure it covers the bundle stuff)

**Comment by holman** [comment]
You maybe want to just copypasta that in for this pull (and then maybe add some of the bundle stuff too)? I wish it were a bit easier to keep this file pinned to that one, but I doubt it changes all too frequently anyway.

**Comment by alias1** [comment]
(This is a bit of a running mind dump, so hopefully can follow it)

So having a little read further into my dotfiles, it seems that by way of [antigen](https://github.com/zsh-users/antigen)/[oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/) i'm sourcing [brew](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/brew) and [brew-cask](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/brew-cask) as well.

antigen let's you source from any repo, so the easiest way to stay up to date with the official brew completions should be something like:

```antigen bundle Homebrew/homebrew Library/Contributions/brew_zsh_completion.zsh```

(which has the less than desirable effect of re-cloning the homebrew repo into `.antigen`, ~68mb)

Making use of the 'local plugin' features, we could do something like:

```
antigen bundle $(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh --no-local-clone
```

It looks like you're currently loading these _completion files in [zsh/config](https://github.com/holman/dotfiles/blob/master/zsh/config.zsh#L12), though [zsh/zshrc.symlink](https://github.com/holman/dotfiles/blob/master/zsh/zshrc.symlink#L31) also mentions autoload, which then runs all the `completion.zsh` files.

It almost looks like including the _completion files loaded by the `config.zsh` line might be an old method that you superceded with the `completion.zsh` method?

Looking at the [git/completion.zsh](https://github.com/holman/dotfiles/blob/master/git/completion.zsh#L4) you're manually sourcing from the homebrew zsh completions folder. It could make sense to add this to the FPATH used in `config.zsh` (for fully automatic loading), or perhaps wrap it up into a nicer helper function to ease loading elsewhere? (though in my trying to do that, it had errors like `_default:compcall:12: can only be called from completion function`)

Actually, fixing up git/completion.zsh so it actually runs (brew not executed when in ', _git file is a symlink so need -e instead of -f)

```
completion="$(brew --prefix)/share/zsh/site-functions/_git"

if [[ -e $completion ]]
then
  source $completion
fi
```

I get the same errors I had when trying to write a nicer 'load' function. Does this work for you? (the rbenv one seems to because the whole thing is directly in completions.zsh)

```
Loading completions..
  /Users/devalias/.dotfiles/git/completion.zsh
zsh:12: command not found: ___main
_default:compcall:12: can only be called from completion function
```

So far, cleanest solution to me (ignoring the other bugs) would be to symlink something like this in the functions folder (replacing the current `_brew`)

```
ln -s $(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh _brew
```

**Comment by holman** [comment]
> I get the same errors I had when trying to write a nicer 'load' function. Does this work for you? (the rbenv one seems to because the whole thing is directly in completions.zsh)

Seems to work for me.

All of this completion stuff is kind of a black box for me; I've never really had the time to sit down and really sort things out. It's mostly — as you've seen — a bunch of things layered on top of each other, and they don't tend to work very well sometimes either (#210).

**Comment by alias1** [comment]
Haha yeah, you and me both tbh. Sunk a bunch of hours into trying to write some better ones, but ultimately have about as little idea what i'm doing with it as when I started.

**Comment by holman** [comment]
Just going to go with what you have right now; we can add to it later if people would like. :)

Thanks for looking into all of this!

**Comment by alias1** [comment]
Sounds good to me :) No worries.

Sent from Outlook Mobile




On Mon, Feb 15, 2016 at 11:52 AM -0800, "Zach Holman" <notifications@github.com> wrote:












Merged #225.

**Pull request merged**
