### PR TITLE
fix / in bootstrap, rearrange prompt.zsh

### PR DESCRIPTION
**Pull request by taherio**
1) There seems to be an extra '/' in the bootstrap script
2) prompt.zsh needed re arrangement
3) added export to rvm to zshrc.symlink

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
On the extra `/`, see #186 - it's there to fix issues with symlinked .dotfiles.

On rvm, you'll probably want to add that to a new file in a topic folder like `ruby/rvm.zsh` (similar to how rbenv setup is in `ruby/rbenv.zsh`).

**Comment by taherio** [comment]
for #186 , I would say it's more cleaner if we use : 
"for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')" 
which will solve the problem without having to add extra trailing slash. Also the symlinks will look much better :) 

For the rvm you are right :+1: I will re do it in a separate commit later

I already updated the bootstrap file and reverted the zshrc.symlink

**Comment by wackywendell** [comment]
Yes, that does look cleaner — I didn't know about `-H`; you learn something new every day!

Is that available cross-platform? I see it in both my Mac `find` (`BSD find`), and in my Linux virtual machine `find` (`GNU find 4.4.2`), so it looks like it...

**Comment by wackywendell** [comment]
To answer my own question: the `-H` option is [in the POSIX standard](http://pubs.opengroup.org/onlinepubs/009695399/utilities/find.html), so all is well!

**Comment by taherio** [comment]
yup ! , the three options ( -H , -L , -P ) are universal, even thought (-P is not in the POSIX standard but it's the default behavior for find command if no option is specified )

**Comment by taherio** [comment]
#184

**Pull request closed without merging**
